### ISSUE TITLE
The two buttons "Export Location" and "Export" do not appear in the dialog.

### ISSUE THREAD

**Issue by paul-bayleaf** [rism-digital/musescore-mei#1]
Musescore 3.6.2
QT 5.15.2
Linux openSUSE 15.4

The two buttons "Export Location" and "Export" do not appear in the dialog.

Looking at export_mei.qml I found I could get it working by either deleting the two Button's "background: Rectangle" blocks, as these don't affect function, only appearance.  Or by adding

contentItem: Text {
                text: parent.text
               verticalAlignment: Text.AlignVCenter
            }

To each Button.

I'm not very familiar with qml, but looking at the documentation:

https://doc.qt.io/qt-5/qtquickcontrols2-customize.html#customizing-button

Seems to imply that when customizing a button with background: then a contentItem: is also required.

**Comment by ahankinson** [comment]
Thanks! Do you feel like you could contribute this as a pull request?

**Comment by paul-bayleaf** [comment]
OK, will do.
